# Generated by Django 5.2.1 on 2025-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lat', models.FloatField()),
                ('current_long', models.FloatField()),
                ('destination_district', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
            ],
        ),
    ]
